# Site settings
title: Raphael Fabeni
name: Raphael Fabeni
email: rapha.fabeni@gmail.com
description: "A brazilian front-end developer who loves the web, electronic music and travels."
baseurl: "/"
url: "https://www.raphaelfabeni.com"
exclude: ['node_modules', 'package.json', 'bin', 'README.md', 'script.bash', 'Gemfile.lock', 'Gemfile', 'start.bash', 'src']

# Build settings
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
source:      .
destination: ./_site
permalink:   /:title/

plugins:
  - jekyll-gist
  - octopress-debugger

blog:
  en: '/blog/'
  pt-br: '/pt-br/blog/'

gist:
  noscript: false

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []


# thankful_eyes
# base16.dark
# base16.solarized
# gruvbox.light
