---
title: Raphael Fabeni
name: Raphael Fabeni
email: rapha.fabeni@gmail.com
description: A brazilian front-end developer who loves the web, electronic music and
  travels.
baseurl: ''
url: https://www.raphaelfabeni.com
exclude:
- node_modules
- package.json
- bin
- README.md
- script.bash
- Gemfile.lock
- Gemfile
- start.bash
- src
permalink: "/:title/"
markdown: kramdown
kramdown:
  input: GFM
source: "."
destination: "./_site"
plugins:
- jekyll-gist
- octopress-debugger
- jekyll-sitemap
blog:
  en: "/blog/"
  pt-br: "/pt-br/blog/"
collections:
  category:
    output: true
    permalink: /:title/
gist:
  noscript: false
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
dictionary:
  en:
    all_categories: 'All'
  pt-br:
    all_categories: 'Tudo'
categories_list:
  en:
    css:
      title: "CSS"
      permalink: /en/css/
    js:
      title: "JavaScript"
      permalink: /en/javascript/
    git:
      title: "Git"
      permalink: /en/git/
    html:
      title: "HTML"
      permalink: /en/html/
    dev-life:
      title: "Dev Life"
      permalink: /en/dev-life/
    user-experience:
      title: "User Experience"
      permalink: /en/user-experience/
    wordpress:
      title: "WordPress"
      permalink: /en/wordpress/
    projects:
      title: "Projects"
      permalink: /en/projects/
  pt-br:
    css:
      title: "CSS"
      permalink: /pt-br/css/
    js:
      title: "JavaScript"
      permalink: /pt-br/javascript/
    git:
      title: "Git"
      permalink: /pt-br/git/
    html:
      title: "HTML"
      permalink: /pt-br/html/
    dev-life:
      title: "Dev Life"
      permalink: /pt-br/dev-life/
    user-experience:
      title: "User Experience"
      permalink: /pt-br/user-experience/
    wordpress:
      title: "WordPress"
      permalink: /pt-br/wordpress/
    projetos:
      title: "Projetos"
      permalink: /pt-br/projetos/
