# Site settings
title: Raphael Fabeni
name: Raphael Fabeni
email: rapha.fabeni@gmail.com
description: "A brazilian front-end developer who loves the web, electronic music and travels."
baseurl: "/"
url: "https://www.raphaelfabeni.com.br"
exclude: ['node_modules', 'package.json', 'bin', 'README.md', 'script.bash', 'Gemfile.lock', 'Gemfile', 'start.bash', 'src']

# Build settings
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  # syntax_highlighter: rouge
source:      .
destination: ./_site
permalink:   /:title/
gems:
  - jekyll-gist
gist:
  noscript: false
collections:
  category:
    output: true


# thankful_eyes
# base16.dark
# base16.solarized
# gruvbox.light
